# Generated by Django 5.1.1 on 2024-09-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('feed_low_level_switch', models.BooleanField(default=False)),
                ('product_high_high_level_switch', models.BooleanField(default=False)),
                ('product_high_level_switch', models.BooleanField(default=False)),
                ('feed_low_pressure_switch', models.BooleanField(default=False)),
                ('system_high_pressure_switch', models.BooleanField(default=False)),
                ('pre_treatment_interlock', models.BooleanField(default=False)),
                ('remote_run', models.BooleanField(default=False)),
                ('chemical_switch1', models.BooleanField(default=False)),
                ('chemical_switch2', models.BooleanField(default=False)),
                ('chemical_switch3', models.BooleanField(default=False)),
                ('chemical_switch4', models.BooleanField(default=False)),
                ('chemical_switch5', models.BooleanField(default=False)),
                ('permeate_flow', models.FloatField(blank=True, null=True)),
                ('reject_flow', models.FloatField(blank=True, null=True)),
                ('recirculation_flow', models.FloatField(blank=True, null=True)),
                ('feed_flow', models.FloatField(blank=True, null=True)),
                ('permeate_conductivity', models.FloatField(blank=True, null=True)),
                ('feed_conductivity', models.FloatField(blank=True, null=True)),
                ('pre_filter_pressure', models.FloatField(blank=True, null=True)),
                ('post_filter_pressure', models.FloatField(blank=True, null=True)),
                ('system_pressure', models.FloatField(blank=True, null=True)),
                ('interstage_pressure', models.FloatField(blank=True, null=True)),
                ('reject_pressure', models.FloatField(blank=True, null=True)),
                ('feed_orp', models.FloatField(blank=True, null=True)),
                ('feed_ph', models.FloatField(blank=True, null=True)),
                ('product_ph', models.FloatField(blank=True, null=True)),
                ('feed_inlet_valve', models.BooleanField(default=False)),
                ('flush_valve', models.BooleanField(default=False)),
                ('bypass_valve', models.BooleanField(default=False)),
                ('divert_valve', models.BooleanField(default=False)),
                ('feed_pump', models.BooleanField(default=False)),
                ('high_pressure_pump', models.BooleanField(default=False)),
                ('chemical_tank1', models.BooleanField(default=False)),
                ('chemical_tank2', models.BooleanField(default=False)),
                ('chemical_tank3', models.BooleanField(default=False)),
                ('chemical_tank4', models.BooleanField(default=False)),
                ('chemical_tank5', models.BooleanField(default=False)),
                ('system_running', models.BooleanField(default=False)),
                ('fault_active', models.BooleanField(default=False)),
            ],
        ),
    ]
